dbt_bq:
  outputs:
    dev:
      dataset: dbt_bq
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ var('key_file_dir') }}"
      location: "{{ var('bigquery_location') }}"
      method: service-account
      priority: interactive
      project: "{{ var('project_id') }}"
      threads: 1
      type: bigquery
  target: dev
